export default{
  Quote: 'Quote',
  NewOrder: 'New Order',
  OrderBook: 'Order Book',
  Portfolio: 'Portfolio',
  More : 'More',
  Account : 'Account',
  PriceAlert : 'Price Alert',
  Markets: 'Markets',
  Passwords : 'Passwords',
  Contacts : 'Contacts',
  Help : 'Help',
  Messages : 'Messages',
  FundTransfer : 'Fund Transfer',
  Services : 'Services',
  Transactions : 'Transactions',
  Settings : 'Settings',
  Watchlists: 'Watchlists',
  '':'',
}
